---
title: "Dominic Culver's Homepage"
format: html
# html:
#   include-in-header: |
#     <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
# theme:
#     light: cosmo
#     dark: [cosmo, theme-dark.scss]
---

<!-- # Who I am -->

**Email Address:** dominic period culver at gmail dot com

Welcome to my homepage! Here you will find some information about me and some of the things I have worked on. If anything here piques your interest, please feel free to reach out!

## About Me

I am a mathematician by training and I got my PhD in 2017 from the University of Notre Dame. I then went on to do postdocs first at the University of Illinois, Urbana-Champaign, and then another postdoc at the Max-Planck-Institüt für Mathematik. My mathematical research interests were all within what is known as stable homotopy theory, and I was particular interested in using ideas around elliptic curves and modular forms to understand complex structures in the stable homotopy groups of spheres.

In 2023, I decided to take the leap and transition into tech. I worked at an early legal AI startup for a year and half where I learned a lot of cool things about software and LLMs. My current interests are around ML and AI broadly, and NLP and LLMs more specifically. I am interested in building new and exciting things with these technologies while also using mathematical background to better understand LLMs in theory. 

I am currently looking for new opportunities which utilize my mathematical and research background and within AI/ML. I am also always happy to collaborate or discuss research ideas, please feel free to peruse my website and reach out!

<!-- Below you can find links to my mathematical (and some LLM) research articules I wrote or participated in, some courses I taught, and some notes from talks I gave. You can also find my blog (forthcoming).

- [Research Papers and Preprints](research/research.html)
- [Teaching](teaching/teaching.html)
- [Notes & Talks](notes/notes.html) -->

